# Generated by Django 4.2.5 on 2023-09-15 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ("customer_name", "email")},
        ),
    ]
