# Generated by Django 4.2.5 on 2023-09-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_account_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="John Doe", max_length=100),
                ),
                (
                    "chosen_name",
                    models.CharField(help_text="John", max_length=40),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="john.doe@gmail.com",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "ordering": ("full_name", "chosen_name", "email"),
            },
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ("alias", "identifier")},
        ),
        migrations.RemoveField(
            model_name="account",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
        migrations.AddField(
            model_name="account",
            name="alias",
            field=models.CharField(
                default="my.alias.account",
                help_text="my.alias.account",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="identifier",
            field=models.CharField(
                default="111222333444555",
                help_text="123456789012345678901",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="customer.customerdata",
            ),
            preserve_default=False,
        ),
    ]
