# Generated by Django 4.2.5 on 2023-09-19 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_customerdata_alter_account_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerdata",
            options={
                "ordering": ("full_name", "chosen_name", "email"),
                "verbose_name": "customer data",
                "verbose_name_plural": "customers data",
            },
        ),
    ]
