# Generated by Django 4.2.5 on 2023-09-19 21:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0004_alter_customerdata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("total_balance", models.FloatField(help_text="999.99")),
                (
                    "average_debit_amount",
                    models.FloatField(help_text="123.50"),
                ),
                (
                    "average_credit_amount",
                    models.FloatField(help_text="123.50"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="customer.account",
                    ),
                ),
            ],
            options={
                "ordering": ("account", "-created"),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(help_text="123", max_length=50),
                ),
                (
                    "day",
                    models.IntegerField(
                        help_text="1-31",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="1-12",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("amount", models.FloatField(help_text="123.45")),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transaction.summary",
                    ),
                ),
            ],
            options={
                "ordering": ("-summary", "-month", "-day"),
            },
        ),
    ]
